name: 'Get & Cache dependencies'
description: 'Get dependencies (via npm) & cache them'
inputs:
  caching_decision:
     description: "Wheather Cache dependencies (Y/N)"
     required: false
     default: 'true'
outputs:
   used-cache:
      description: "Wheather Cache has been used or not !"    
      value:  ${{ steps.install.outputs.CacheOutput}}
runs:
   using: 'composite'
   steps:
    - name: Cache dependencies
      if: inputs.caching_decision == 'true'
      id: cache
      uses: actions/cache@v3
      with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching_decision != 'true'
      run: | 
       npm ci
       echo "::set-output name=CacheOutput::'${{inputs.caching_decision}}'"
      shell: bash