name: 'Get & Cache dependencies'
description: 'Get dependencies (via npm) & cache them'
inputs:
  caching_decision:
     description: "Want Cache dependencies (Y/N)"
     required: false
     default: 'true'
runs:
   using: 'composite'
   steps:
    - name: Cache dependencies
      if: inputs.caching_decision == 'true'
      id: cache
      uses: actions/cache@v3
      with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching_decision != 'true'
      run: npm ci
      shell: bash